const BlogData = [
    {
        id: 1,
        date: "March 01 2022",
        catgeory: "Business",
        title: "The Most Advance Business Plan",
        cover: "images/blog1.jpg",
        para: "Business tourism or business travel is a more limited and focused subset of regular tourism. During business tourism (traveling), individuals are still working and being paid, but are doing so away from both their workplace and home. Some definitions of tourism exclude business travel",
        desc:"Business tourism is a lucrative, fast-growing segment of the world's largest industry sector. Good niches in business tourism exist for developing and transition economies. These countries can market themselves as cost-effective, yet exotic locales, where corporate objectives can be met in a rejuvenating setting.",
    },
    {
        id: 2,
        date: "March 01 2022",
        catgeory: "Business",
        title: "The Most Advance Business Plan",
        cover: "images/blog2.jpg",
        para: "Business tourism or business travel is a more limited and focused subset of regular tourism. During business tourism (traveling), individuals are still working and being paid, but are doing so away from both their workplace and home. Some definitions of tourism exclude business travel",
        desc:"Business tourism is a lucrative, fast-growing segment of the world's largest industry sector. Good niches in business tourism exist for developing and transition economies. These countries can market themselves as cost-effective, yet exotic locales, where corporate objectives can be met in a rejuvenating setting.",
    },
    {
        id: 3,
        date: "March 01 2022",
        catgeory: "Business",
        title: "The Most Advance Business Plan",
        cover: "images/blog3.jpg",
        para: "Business tourism or business travel is a more limited and focused subset of regular tourism. During business tourism (traveling), individuals are still working and being paid, but are doing so away from both their workplace and home. Some definitions of tourism exclude business travel",
        desc:"Business tourism is a lucrative, fast-growing segment of the world's largest industry sector. Good niches in business tourism exist for developing and transition economies. These countries can market themselves as cost-effective, yet exotic locales, where corporate objectives can be met in a rejuvenating setting.",
    },
    {
        id: 4,
        date: "March 01 2022",
        catgeory: "Business",
        title: "The Most Advance Business Plan",
        cover: "images/blog4.jpg",
        para: "Business tourism or business travel is a more limited and focused subset of regular tourism. During business tourism (traveling), individuals are still working and being paid, but are doing so away from both their workplace and home. Some definitions of tourism exclude business travel",
        desc:"Business tourism is a lucrative, fast-growing segment of the world's largest industry sector. Good niches in business tourism exist for developing and transition economies. These countries can market themselves as cost-effective, yet exotic locales, where corporate objectives can be met in a rejuvenating setting.",
    },
    {
        id: 5,
        date: "March 01 2022",
        catgeory: "Business",
        title: "The Most Advance Business Plan",
        cover: "images/blog5.jpg",
        para: "Business tourism or business travel is a more limited and focused subset of regular tourism. During business tourism (traveling), individuals are still working and being paid, but are doing so away from both their workplace and home. Some definitions of tourism exclude business travel",
        desc:"Business tourism is a lucrative, fast-growing segment of the world's largest industry sector. Good niches in business tourism exist for developing and transition economies. These countries can market themselves as cost-effective, yet exotic locales, where corporate objectives can be met in a rejuvenating setting.",
    },
    {
        id: 6,
        date: "March 01 2022",
        catgeory: "Business",
        title: "The Most Advance Business Plan",
        cover: "images/blog6.jpg",
        para: "Business tourism or business travel is a more limited and focused subset of regular tourism. During business tourism (traveling), individuals are still working and being paid, but are doing so away from both their workplace and home. Some definitions of tourism exclude business travel",
        desc:"Business tourism is a lucrative, fast-growing segment of the world's largest industry sector. Good niches in business tourism exist for developing and transition economies. These countries can market themselves as cost-effective, yet exotic locales, where corporate objectives can be met in a rejuvenating setting.",
    },
    {
        id: 7,
        date: "March 01 2022",
        catgeory: "Business",
        title: "The Most Advance Business Plan",
        cover: "images/blog7.jpg",
        para: "Business tourism or business travel is a more limited and focused subset of regular tourism. During business tourism (traveling), individuals are still working and being paid, but are doing so away from both their workplace and home. Some definitions of tourism exclude business travel",
        desc:"Business tourism is a lucrative, fast-growing segment of the world's largest industry sector. Good niches in business tourism exist for developing and transition economies. These countries can market themselves as cost-effective, yet exotic locales, where corporate objectives can be met in a rejuvenating setting.",
    },
    {
        id: 8,
        date: "March 01 2022",
        catgeory: "Business",
        title: "The Most Advance Business Plan",
        cover: "images/blog8.jpg",
        para: "Business tourism or business travel is a more limited and focused subset of regular tourism. During business tourism (traveling), individuals are still working and being paid, but are doing so away from both their workplace and home. Some definitions of tourism exclude business travel",
        desc:"Business tourism is a lucrative, fast-growing segment of the world's largest industry sector. Good niches in business tourism exist for developing and transition economies. These countries can market themselves as cost-effective, yet exotic locales, where corporate objectives can be met in a rejuvenating setting.",
    },
    {
        id: 9,
        date: "March 01 2022",
        catgeory: "Business",
        title: "The Most Advance Business Plan",
        cover: "images/blog9.jpg",
        para: "Business tourism or business travel is a more limited and focused subset of regular tourism. During business tourism (traveling), individuals are still working and being paid, but are doing so away from both their workplace and home. Some definitions of tourism exclude business travel",
        desc:"Business tourism is a lucrative, fast-growing segment of the world's largest industry sector. Good niches in business tourism exist for developing and transition economies. These countries can market themselves as cost-effective, yet exotic locales, where corporate objectives can be met in a rejuvenating setting.",
    },
]
export default BlogData