const BlogData = [
    {
        id: 1,
        date: "April 01 2023",
        catgeory: "Chain hotels",
        title: "Marriott International",
        cover: "images/blog1.jpg",
        para: "Chain Hotel: Also known as a “branded hotel,” a chain hotel is affiliated with a brand that may have strict guidelines for amenities and design. Some chain hotels are part of a larger ownership group, while other chain hotels have independent owners but follow the same brand standards. Popular hotel chains are Courtyard, Holiday Inn, and Westin.",
        desc:"Chain Hotel: Also known as a “branded hotel,” a chain hotel is affiliated with a brand that may have strict guidelines for amenities and design. Some chain hotels are part of a larger ownership group, while other chain hotels have independent owners but follow the same brand standards. Popular hotel chains are Courtyard, Holiday Inn, and Westin..",
    },
    {
        id: 2,
        date: "March 01 2023",
        catgeory: "Boutique Hotel",
        title: "Vision Resort",
        cover: "images/blog2.jpg",
        para: "A hotel that incorporates unique design and personalized service, often with a theme or local influences. Boutique hotels are usually small (under 100 rooms) and independently owned, though some boutique hotels are part of collections like Leading Hotels of the World or chains like the Curio Collection by Hilton.",
        desc:"A hotel that incorporates unique design and personalized service, often with a theme or local influences. Boutique hotels are usually small (under 100 rooms) and independently owned, though some boutique hotels are part of collections like Leading Hotels of the World or chains like the Curio Collection by Hilton.",
    },
    {
        id: 3,
        date: "October 01 2022",
        catgeory: "Airport Hotel",
        title: "Blue Moon",
        cover: "images/blog3.jpg",
        para: "An airport hotel is located near - you guessed it! - an airport. Airport hotels usually provide free airport transportation for a seamless transfer. Also known as a condo hotel, apart-hotels are made up of apartment-style units which can contain full kitchens and several bedrooms. Apart-hotels offer all the services of a hotel, like a front desk and housekeeping.",
        desc:"An airport hotel is located near - you guessed it! - an airport. Airport hotels usually provide free airport transportation for a seamless transfer. Also known as a condo hotel, apart-hotels are made up of apartment-style units which can contain full kitchens and several bedrooms. Apart-hotels offer all the services of a hotel, like a front desk and housekeeping.",
    },
    {
        id: 4,
        date: "September 01 2022",
        catgeory: "Business Hotel",
        title: "Hotel Grizzly.",
        cover: "images/blog4.jpg",
        para: "Business tourism or business travel is a more limited and focused subset of regular tourism. During business tourism (traveling), individuals are still working and being paid, but are doing so away from both their workplace and home. Some definitions of tourism exclude business travel.These properties cater to business travelers and are located near business districts, airports, or convention centers. On-site amenities include meeting rooms, business centers, and restaurants for breakfast on the go.",
        desc:"Business tourism is a lucrative, fast-growing segment of the world's largest industry sector. Good niches in business tourism exist for developing and transition economies. These countries can market themselves as cost-effective, yet exotic locales, where corporate objectives can be met in a rejuvenating setting.These properties cater to business travelers and are located near business districts, airports, or convention centers. On-site amenities include meeting rooms, business centers, and restaurants for breakfast on the go.",
    },
    {
        id: 5,
        date: "August 01 2022",
        catgeory: "Casino Hotel",
        title: "Aliante Casino and Hotel.",
        cover: "images/blog5.jpg",
        para: "Feeling lucky? Casino hotels have on-site casinos, usually in addition to restaurants, bars, spas, and shops. Las Vegas and Atlantic City have high concentrations of casino hotels.A casino hotel is an establishment consisting of a casino with temporary lodging provided in an on-premises hotel. Customers receive the benefits of both gambling facilities and lodging. Since the casino and hotel are located on the same premises, a gambler's necessities can be provided for in one location.",
        desc:"Feeling lucky? Casino hotels have on-site casinos, usually in addition to restaurants, bars, spas, and shops. Las Vegas and Atlantic City have high concentrations of casino hotels.A casino hotel is an establishment consisting of a casino with temporary lodging provided in an on-premises hotel. Customers receive the benefits of both gambling facilities and lodging. Since the casino and hotel are located on the same premises, a gambler's necessities can be provided for in one location.",
    },
    {
        id: 6,
        date: "July 01 2022",
        catgeory: "BEco Hotel",
        title: "Alila Diwa",
        cover: "images/blog6.jpg",
        para: "Staying in a hotel doesn’t need to hurt the environment. Eco hotels range in size and style, but they all have a focus on environmental-friendliness. Eco hotels might come with limited housekeeping service, organic restaurants, LEED-certified architecture, and sustainable decor.a hotel with features and services designed not to be harmful to the environment For the politically correct couple, this brand-new eco-hotel—south of Puerto Vallarta on the Pacific coast—offers a guilt-free honeymoon. Everything is recycled; the water is solar-heated, the produce organic.",
        desc:"Staying in a hotel doesn’t need to hurt the environment. Eco hotels range in size and style, but they all have a focus on environmental-friendliness. Eco hotels might come with limited housekeeping service, organic restaurants, LEED-certified architecture, and sustainable decor.a hotel with features and services designed not to be harmful to the environment For the politically correct couple, this brand-new eco-hotel—south of Puerto Vallarta on the Pacific coast—offers a guilt-free honeymoon. Everything is recycled; the water is solar-heated, the produce organic.",
    },
    {
        id: 7,
        date: "June 01 2022",
        catgeory: "Family Hotel",
        title: "Four Seasons Resort",
        cover: "images/blog7.jpg",
        para: "Traveling with the kids is easier when you choose a family hotel, which are found in popular vacation destinations like Orlando. These properties offer family-friendly rooms with bunk beds or separate bedrooms, restaurants with kid-approved menu choices, childcare or day camps, and activities for all ages.",
        desc:"Traveling with the kids is easier when you choose a family hotel, which are found in popular vacation destinations like Orlando. These properties offer family-friendly rooms with bunk beds or separate bedrooms, restaurants with kid-approved menu choices, childcare or day camps, and activities for all ages.",
    },
    {
        id: 8,
        date: "May 01 2022",
        catgeory: "Microstay Hotel",
        title: "Hotel Magnet Residency",
        cover: "images/blog8.jpg",
        para: "Microstay hotels are hotels that can be booked by the hour, not just by the night. Inspired, in part, by capsule hotels, they are sometimes known as day-stay or short-stay hotels. They first became popular in Europe but can now be found in most travel hubs across the world. Need a place to rest your head for a few hours? Microstay hotels can be booked by the hour, which is ideal for travelers with long layovers or quick turnaround times that don’t align with the standard check-in and check-out policies.",
        desc:"Microstay hotels are hotels that can be booked by the hour, not just by the night. Inspired, in part, by capsule hotels, they are sometimes known as day-stay or short-stay hotels. They first became popular in Europe but can now be found in most travel hubs across the world. Need a place to rest your head for a few hours? Microstay hotels can be booked by the hour, which is ideal for travelers with long layovers or quick turnaround times that don’t align with the standard check-in and check-out policies.",
    },
    {
        id: 9,
        date: "April 01 2022",
        catgeory: "Country House Hotel",
        title: "Inn Of Dreams",
        cover: "images/blog9.jpg",
        para: "Popular in the English countryside, these tranquil hotels provide the ideal setting for a weekend away from the hustle and bustle of the big city. Country house hotels offer comfort food, afternoon tea, and activities like hunting and horseback riding.This classic German accommodation offers guestrooms and a restaurant or tavern. These properties feature traditional architecture and are found in small towns throughout Germany.",
        desc:"Popular in the English countryside, these tranquil hotels provide the ideal setting for a weekend away from the hustle and bustle of the big city. Country house hotels offer comfort food, afternoon tea, and activities like hunting and horseback riding.This classic German accommodation offers guestrooms and a restaurant or tavern. These properties feature traditional architecture and are found in small towns throughout Germany.",
    },
]
export default BlogData